force-app/main/default/objects/PromptSetting__mdt/PromptSetting__mdt.object-meta.xml
<CustomObject>
    <label>Prompt Setting</label>
    <pluralLabel>Prompt Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PromptSetting__mdt/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <description>Name of the ApexClass to invoke in order to get the chat completion</description>
    <label>ApexClassName</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Frequency_Penalty__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Penalty__c</fullName>
    <description>Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model&apos;s likelihood to repeat the same line verbatim.</description>
    <label>Frequency Penalty</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Max_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Max_Tokens__c</fullName>
    <description>The maximum number of tokens that can be generated in the completion.</description>
    <label>Max Tokens</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>This field determines which model to use for making API Call.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Presence_Penalty__c.field-meta.xml
<CustomField>
    <fullName>Presence_Penalty__c</fullName>
    <description>Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model&apos;s likelihood to talk about new topics.</description>
    <label>Presence Penalty</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Temprature__c.field-meta.xml
<CustomField>
    <fullName>Temprature__c</fullName>
    <description>The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.</description>
    <label>Temprature</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Top_P__c.field-meta.xml
<CustomField>
    <fullName>Top_P__c</fullName>
    <description>An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.</description>
    <label>Top_P</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AI_Case_RoutingTest.cls
@isTest
public with sharing class AI_Case_RoutingTest {

  private static PromptSetting__mdt getSettings(String psDeveloperName) {
    return [SELECT Id, DeveloperName, Instructions__c, Named_Credential__c, 
                    ApexClassName__c,Temprature__c, Top_P__c, Frequency_Penalty__c,
                    Presence_Penalty__c, Max_Tokens__c  
            FROM PromptSetting__mdt 
            WHERE DeveloperName = :psDeveloperName 
            LIMIT 1];
  }

  @isTest
  static void testValidInputs() {
    PromptSetting__mdt ps = getSettings('Country_identification');
    Map<String, Object> inputs = new Map<String, Object>{
      'settings' => ps,
      'prompt' => 'This is a test prompt for Case Routing'
    };

    // Set mock callout class
    String mockJsonResponse = '{"choices":[{"message":{"content":"FR"}}]}';
    MockHttpResponses mockResponse = new MockHttpResponses(200, 'OK', mockJsonResponse);
    mockResponse.setHeaders(new Map<String, String>{'Content-Type' => 'application/json'});
    Test.setMock(HttpCalloutMock.class, mockResponse);
    Test.startTest();
    AI_Case_Routing aiCaseRouting = new AI_Case_Routing();
    Map<String, String> result = aiCaseRouting.getChatCompletion(inputs);
    Test.stopTest();
    // Assert
    Assert.areEqual('FR', result.get('probableCountry'), 'Invalid response from AI Case Routing from country determination');
  }

  @isTest
  static void apiCallErrorTest() {
    PromptSetting__mdt ps = getSettings('Country_identification');
    Map<String, Object> inputs = new Map<String, Object>{
      'settings' => ps,
      'prompt' => 'This is a test prompt for Case Routing'
    };

    // Set mock callout class
    //this String will cause a deserialization error
    String invalidJsonResponse = '{"choices":[{"message":{"content":"Bad Request"}}}';
    MockHttpResponses mockResponse = new MockHttpResponses(400, 'Bad Request', invalidJsonResponse);
    mockResponse.setHeaders(new Map<String, String>{'Content-Type' => 'application/json'});
    Test.setMock(HttpCalloutMock.class, mockResponse);

    AI_Case_Routing aiCaseRouting = new AI_Case_Routing();
    try {
      Map<String, String> result = aiCaseRouting.getChatCompletion(inputs);
    } catch (AI_Case_Routing.AI_Case_RoutingException e) {
      // Assert that the exception is thrown
      Assert.isTrue(e.getMessage().startsWith('Impossible to get chat completion from the API'), 'Incorrect error thrown');
    }
  }

  @isTest
  static void testInvalidInputs() {
    // Test with null inputs
    AI_Case_Routing aiCaseRouting = new AI_Case_Routing();
    try {
      aiCaseRouting.getChatCompletion(null);
    } catch (AI_Case_Routing.AI_Case_RoutingException e) {
      Assert.areEqual('Invalid input data for chat completion', e.getMessage(), 'Incorrect error thrown for null inputs');
    }
  }
}