force-app/main/default/objects/PromptSetting__mdt/PromptSetting__mdt.object-meta.xml
<CustomObject>
    <label>Prompt Setting</label>
    <pluralLabel>Prompt Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PromptSetting__mdt/fields/Frequency_Penalty__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Penalty__c</fullName>
    <description>Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model&apos;s likelihood to repeat the same line verbatim.</description>
    <label>Frequency Penalty</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Max_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Max_Tokens__c</fullName>
    <description>The maximum number of tokens that can be generated in the completion.</description>
    <label>Max Tokens</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>This field determines which model to use for making API Call.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Presence_Penalty__c.field-meta.xml
<CustomField>
    <fullName>Presence_Penalty__c</fullName>
    <description>Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model&apos;s likelihood to talk about new topics.</description>
    <label>Presence Penalty</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Temprature__c.field-meta.xml
<CustomField>
    <fullName>Temprature__c</fullName>
    <description>The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.</description>
    <label>Temprature</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PromptSetting__mdt/fields/Top_P__c.field-meta.xml
<CustomField>
    <fullName>Top_P__c</fullName>
    <description>An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.</description>
    <label>Top_P</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AI_MsOpenAiCompletion.cls
/* Parent class for all Microsoft OpenAI Apex classes
 * implementing the different AI use cases.
 * This abstract class contains all common methods and properties 
 * shared by concrete implementations, such as request building, 
 * response parsing, and logging, to address various AI use cases.
 */
public with sharing abstract class AI_MsOpenAiCompletion {

  protected final Integer HTTP_TIMEOUT = 120000;
  protected final String KEY_CHOICES = 'choices';
  protected final String KEY_ROLE = 'role';
  protected final String KEY_CONTENT = 'content';
  protected final String KEY_FREQ_PEN = 'frequency_penalty';
  protected final String KEY_MAX_TOK = 'max_tokens';
  protected final String KEY_MESSAGE = 'message';
  protected final String KEY_MESSAGES = 'messages';
  protected final String KEY_PRES_PEN = 'presence_penalty';
  protected final String KEY_TEMPERATURE = 'temperature';
  protected final String KEY_TOP_P = 'top_p';
  protected final String ROLE_SYSTEM = 'system';
  protected final String ROLE_USER = 'user';
  protected String prompt;
  protected Map<String,String> returnMap = new Map<String,String>();
  protected PromptSetting__mdt ps;
  String requestBodyJson;

  public virtual void init(Map<String, Object> inputs) {
    this.ps = (PromptSetting__mdt) inputs.get('settings');
    this.prompt = (String) inputs.get('prompt');
  }

  public virtual HttpRequest buildHttpRequest(){
    //prepare Request Body data
    List<Object> messages = new List<Object>();
    messages.add(new Map<String, Object>{ KEY_ROLE => ROLE_SYSTEM,
                                          KEY_CONTENT => ps.Instructions__c});
    messages.add(new Map<String, Object>{ KEY_ROLE => ROLE_USER,
                                          KEY_CONTENT => prompt});
    Map<String, Object> requestBodyMap = new Map<String, Object>{KEY_MESSAGES => messages,
                                                                 KEY_TEMPERATURE => ps.Temprature__c,
                                                                 KEY_TOP_P => ps.Top_P__c,
                                                                 KEY_FREQ_PEN => ps.Frequency_Penalty__c,
                                                                 KEY_PRES_PEN => ps.Presence_Penalty__c,
                                                                 KEY_MAX_TOK => Integer.valueOf(ps.Max_Tokens__c) };
    requestBodyJson = JSON.serialize(requestBodyMap);
    //Build Request
    HttpRequest request = new HttpRequest();
    request.setTimeout(HTTP_TIMEOUT);
    request.setEndpoint(ps.Named_Credential__c);
    request.setMethod(Constants.HTTP.HTTP_METHOD_POST);
    request.setHeader(Constants.HTTP.HEADER_CONTENT_TYPE, Constants.HTTP.CONTENT_TYPE_JSON);
    request.setBody(requestBodyJson);

    return request;
  }

  public virtual String parseResponse(HttpResponse response) {
    Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
    List<Object> choices = (List<Object>) responseBody.get(KEY_CHOICES);
    Map<String, Object> message = (Map<String, Object>) ((Map<String, Object>) choices[0]).get(KEY_MESSAGE);
    return (String) message.get(KEY_CONTENT);
  }

  public virtual void logAiEvent(HttpResponse response) {
    // Create log
    Logger.info('AI Use Case: ' + ps.DeveloperName);
    Logger.info('Api endpoint: ' + ps.Named_Credential__c);
    Logger.info('Request body: ' + requestBodyJson);
    Logger.info('Response status: ' + response.getStatus());
    Logger.info('Response body: ' + response.getBody());
    Logger.info('Prompt: ' + ps.Instructions__c);
    Logger.saveLog();
    Logger.flushBuffer();
  }
}